#!/usr/bin/env python3
"""Genera `src/Sanic.Mppp.Plugins/Dominio/Choices.g.cs`: un `enum` de C# por cada
choice global construido, con los valores EXACTOS de su playbook (BP-PP-193: el
código nunca usa el literal numérico). La fuente es `playbooks/choice-global/`.

    python3 herramientas/codigo/generar_enums.py            # escribe el archivo
    python3 herramientas/codigo/generar_enums.py --comprobar  # falla si está desactualizado
"""
import glob
import os
import re
import sys

_AQUI = os.path.dirname(os.path.abspath(__file__))
_RAIZ = os.path.dirname(os.path.dirname(_AQUI))
sys.path.insert(0, os.path.join(os.path.dirname(_AQUI), "construir"))

from _comun import dividir_secciones, leer_texto, nombre_de_archivo, obtener_componente  # noqa: E402

DESTINO = os.path.join(_RAIZ, "src", "Sanic.Mppp.Plugins", "Dominio", "Choices.g.cs")


def pascal(texto):
    """'Rechazada en AS400' -> 'RechazadaEnAS400'; 'No es correo nuevo' -> 'NoEsCorreoNuevo'."""
    partes = [p for p in re.split(r"[^A-Za-z0-9]+", texto) if p]
    nombre = "".join(p if p.isupper() else p[0].upper() + p[1:] for p in partes)
    return nombre if not nombre[0].isdigit() else "_" + nombre


def generar():
    bloques = []
    for ruta in sorted(glob.glob(os.path.join(_RAIZ, "playbooks", "choice-global", "sanic_*.md"))):
        c = obtener_componente(dividir_secciones(leer_texto(ruta)), "choice-global")
        corto = c["nombre"].rsplit("_ch_", 1)[1]
        visible = c["displayname"].split(" - ", 2)[2]
        nombre_enum = pascal(visible)
        miembros, vistos = [], set()
        for op in c["opciones"]:
            m = pascal(op["etiqueta"])
            if m in vistos:
                raise SystemExit(f"{c['nombre']}: dos opciones dan el mismo nombre de miembro {m!r}")
            vistos.add(m)
            miembros.append(f"        /// <summary>{op['etiqueta']}</summary>\n        {m} = {op['valor']},")
        bloques.append(f"    /// <summary>Choice global <c>{c['nombre']}</c> ({c['displayname']}).</summary>\n"
                       f"    public enum {nombre_enum}\n    {{\n" + "\n".join(miembros) + "\n    }")
        _ = corto
    return ("// <auto-generated>\n// Generado por herramientas/codigo/generar_enums.py desde playbooks/choice-global/.\n"
            "// NO editar a mano: cambia el playbook del choice y se vuelve a generar.\n// </auto-generated>\n"
            "namespace Sanic.Mppp.Plugins.Dominio\n{\n" + "\n\n".join(bloques) + "\n}\n")


def main():
    texto = generar()
    if "--comprobar" in sys.argv:
        actual = open(DESTINO, encoding="utf-8").read() if os.path.exists(DESTINO) else ""
        if actual != texto:
            print("Choices.g.cs está desactualizado: correr herramientas/codigo/generar_enums.py")
            return 1
        print("Choices.g.cs está al día")
        return 0
    os.makedirs(os.path.dirname(DESTINO), exist_ok=True)
    open(DESTINO, "w", encoding="utf-8").write(texto)
    print("escrito", os.path.relpath(DESTINO, _RAIZ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
