// <auto-generated>
// Generado por herramientas/codigo/generar_enums.py desde playbooks/choice-global/.
// NO editar a mano: cambia el playbook del choice y se vuelve a generar.
// </auto-generated>
namespace Sanic.Mppp.Plugins.Dominio
{
    /// <summary>Choice global <c>sanic_mppp_ch_banco</c> (CH - MPPP - Banco).</summary>
    public enum Banco
    {
        /// <summary>LAFISE</summary>
        LAFISE = 159460001,
        /// <summary>BAC</summary>
        BAC = 159460002,
        /// <summary>BANPRO</summary>
        BANPRO = 159460003,
        /// <summary>FICOHSA</summary>
        FICOHSA = 159460004,
        /// <summary>BDF</summary>
        BDF = 159460005,
        /// <summary>AVANZ</summary>
        AVANZ = 159460006,
        /// <summary>PRODUZCAMOS</summary>
        PRODUZCAMOS = 159460007,
        /// <summary>ATLANTIDA</summary>
        ATLANTIDA = 159460008,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_clasificacion</c> (CH - MPPP - Clasificacion).</summary>
    public enum Clasificacion
    {
        /// <summary>BAC</summary>
        BAC = 159460001,
        /// <summary>ACH</summary>
        ACH = 159460002,
        /// <summary>CK</summary>
        CK = 159460003,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_efectoregla</c> (CH - MPPP - Efecto de la regla).</summary>
    public enum EfectoDeLaRegla
    {
        /// <summary>Rechaza</summary>
        Rechaza = 159460001,
        /// <summary>Envia a revision</summary>
        EnviaARevision = 159460002,
        /// <summary>Advierte</summary>
        Advierte = 159460003,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_estadofila</c> (CH - MPPP - Estado de la fila).</summary>
    public enum EstadoDeLaFila
    {
        /// <summary>Rechazada en validacion</summary>
        RechazadaEnValidacion = 159460001,
        /// <summary>Sin autorizacion</summary>
        SinAutorizacion = 159460002,
        /// <summary>Validada</summary>
        Validada = 159460003,
        /// <summary>Digitada</summary>
        Digitada = 159460004,
        /// <summary>Aprobada</summary>
        Aprobada = 159460005,
        /// <summary>Rechazada en AS400</summary>
        RechazadaEnAS400 = 159460006,
        /// <summary>Anulada</summary>
        Anulada = 159460007,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_estadosolicitud</c> (CH - MPPP - Estado de la solicitud).</summary>
    public enum EstadoDeLaSolicitud
    {
        /// <summary>Ingresada</summary>
        Ingresada = 159460001,
        /// <summary>No reconocida</summary>
        NoReconocida = 159460002,
        /// <summary>Descartada</summary>
        Descartada = 159460003,
        /// <summary>Rechazada</summary>
        Rechazada = 159460004,
        /// <summary>En proceso</summary>
        EnProceso = 159460005,
        /// <summary>Procesada</summary>
        Procesada = 159460006,
        /// <summary>Cerrada</summary>
        Cerrada = 159460007,
        /// <summary>No es correo nuevo</summary>
        NoEsCorreoNuevo = 159460008,
        /// <summary>Vencida</summary>
        Vencida = 159460009,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_eventobitacora</c> (CH - MPPP - Evento de bitacora).</summary>
    public enum EventoDeBitacora
    {
        /// <summary>Ingresada</summary>
        Ingresada = 159460001,
        /// <summary>Validacion terminada</summary>
        ValidacionTerminada = 159460002,
        /// <summary>Acuse iniciado</summary>
        AcuseIniciado = 159460003,
        /// <summary>Acuse enviado</summary>
        AcuseEnviado = 159460004,
        /// <summary>Fila digitada</summary>
        FilaDigitada = 159460005,
        /// <summary>Fila aprobada</summary>
        FilaAprobada = 159460006,
        /// <summary>Fila devuelta</summary>
        FilaDevuelta = 159460007,
        /// <summary>Fila rechazada en AS400</summary>
        FilaRechazadaEnAS400 = 159460008,
        /// <summary>Fila anulada</summary>
        FilaAnulada = 159460018,
        /// <summary>Procesada</summary>
        Procesada = 159460009,
        /// <summary>Respuesta final iniciada</summary>
        RespuestaFinalIniciada = 159460010,
        /// <summary>Respuesta final enviada</summary>
        RespuestaFinalEnviada = 159460011,
        /// <summary>Cerrada</summary>
        Cerrada = 159460012,
        /// <summary>No reconocida atendida</summary>
        NoReconocidaAtendida = 159460013,
        /// <summary>Descartada</summary>
        Descartada = 159460014,
        /// <summary>Reintento</summary>
        Reintento = 159460015,
        /// <summary>Requiere revision</summary>
        RequiereRevision = 159460016,
        /// <summary>Error</summary>
        Error = 159460017,
        /// <summary>Correo clasificado</summary>
        CorreoClasificado = 159460019,
        /// <summary>Vencida</summary>
        Vencida = 159460020,
        /// <summary>Revision atendida</summary>
        RevisionAtendida = 159460021,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_gestion</c> (CH - MPPP - Gestion).</summary>
    public enum Gestion
    {
        /// <summary>Inclusion</summary>
        Inclusion = 159460001,
        /// <summary>Exclusion</summary>
        Exclusion = 159460002,
        /// <summary>Modificacion</summary>
        Modificacion = 159460003,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_moneda</c> (CH - MPPP - Moneda).</summary>
    public enum Moneda
    {
        /// <summary>COR</summary>
        COR = 159460001,
        /// <summary>USD</summary>
        USD = 159460002,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_nivelregla</c> (CH - MPPP - Nivel de la regla).</summary>
    public enum NivelDeLaRegla
    {
        /// <summary>Solicitud</summary>
        Solicitud = 159460001,
        /// <summary>Registro</summary>
        Registro = 159460002,
        /// <summary>Correo</summary>
        Correo = 159460003,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_origenevento</c> (CH - MPPP - Origen del evento).</summary>
    public enum OrigenDelEvento
    {
        /// <summary>MPPP-REC</summary>
        MPPPREC = 159460001,
        /// <summary>MPPP-ING</summary>
        MPPPING = 159460002,
        /// <summary>MPPP-COM</summary>
        MPPPCOM = 159460003,
        /// <summary>MPPP-ENV</summary>
        MPPPENV = 159460004,
        /// <summary>MPPP-VIG</summary>
        MPPPVIG = 159460005,
        /// <summary>Custom API</summary>
        CustomAPI = 159460006,
        /// <summary>Plugin</summary>
        Plugin = 159460007,
        /// <summary>App</summary>
        App = 159460008,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_resultadoregla</c> (CH - MPPP - Resultado de la regla).</summary>
    public enum ResultadoDeLaRegla
    {
        /// <summary>Cumplida</summary>
        Cumplida = 159460001,
        /// <summary>No cumplida</summary>
        NoCumplida = 159460002,
        /// <summary>Omitida</summary>
        Omitida = 159460003,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_tipoformatoplan</c> (CH - MPPP - Tipo de formato del plan).</summary>
    public enum TipoDeFormatoDelPlan
    {
        /// <summary>06</summary>
        _06 = 159460001,
        /// <summary>10</summary>
        _10 = 159460002,
        /// <summary>11</summary>
        _11 = 159460003,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_tipoidentificacion</c> (CH - MPPP - Tipo de identificacion).</summary>
    public enum TipoDeIdentificacion
    {
        /// <summary>CNA</summary>
        CNA = 159460001,
        /// <summary>CRE</summary>
        CRE = 159460002,
        /// <summary>PAS</summary>
        PAS = 159460003,
        /// <summary>PEX</summary>
        PEX = 159460004,
        /// <summary>RUC</summary>
        RUC = 159460005,
    }

    /// <summary>Choice global <c>sanic_mppp_ch_tipoparametro</c> (CH - MPPP - Tipo de parametro).</summary>
    public enum TipoDeParametro
    {
        /// <summary>Texto</summary>
        Texto = 159460001,
        /// <summary>Numero</summary>
        Numero = 159460002,
        /// <summary>JSON</summary>
        JSON = 159460003,
    }
}
